services:
  db:
    image: postgres:16-alpine
    container_name: rate-my-coach
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rate-my-coach
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rate-my-coach-net

volumes:
  postgres_data:

networks:
  rate-my-coach-net:
